# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tests/protos/mls.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "tests/protos/mls.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
	b'\n\x16tests/protos/mls.proto\x12\x07puremls"4\n\x0bJoinRequest\x12\x10\n\x08identity\x18\x01 \x01(\t\x12\x13\n\x0bkey_package\x18\x02 \x01(\x0c"\x1f\n\x0cJoinResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"J\n\x0eWelcomeMessage\x12\x17\n\x0ftarget_identity\x18\x01 \x01(\t\x12\x0b\n\x03\x65nc\x18\x02 \x01(\x0c\x12\x12\n\nciphertext\x18\x03 \x01(\x0c"!\n\rListenRequest\x12\x10\n\x08identity\x18\x01 \x01(\t"\x05\n\x03\x41\x63k2\xc8\x01\n\x08MLSSwarm\x12:\n\tJoinSwarm\x12\x14.puremls.JoinRequest\x1a\x15.puremls.JoinResponse"\x00\x12\x39\n\x0e\x44\x65liverWelcome\x12\x17.puremls.WelcomeMessage\x1a\x0c.puremls.Ack"\x00\x12\x45\n\x0eListenWelcomes\x12\x16.puremls.ListenRequest\x1a\x17.puremls.WelcomeMessage"\x00\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tests.protos.mls_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
	DESCRIPTOR._loaded_options = None  # type: ignore[attr-defined]
	_globals["_JOINREQUEST"]._serialized_start = 35
	_globals["_JOINREQUEST"]._serialized_end = 87
	_globals["_JOINRESPONSE"]._serialized_start = 89
	_globals["_JOINRESPONSE"]._serialized_end = 120
	_globals["_WELCOMEMESSAGE"]._serialized_start = 122
	_globals["_WELCOMEMESSAGE"]._serialized_end = 196
	_globals["_LISTENREQUEST"]._serialized_start = 198
	_globals["_LISTENREQUEST"]._serialized_end = 231
	_globals["_ACK"]._serialized_start = 233
	_globals["_ACK"]._serialized_end = 238
	_globals["_MLSSWARM"]._serialized_start = 241
	_globals["_MLSSWARM"]._serialized_end = 441
# @@protoc_insertion_point(module_scope)
