# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""


import grpc

from tests.protos import mls_pb2 as tests_dot_protos_dot_mls__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
	from grpc._utilities import first_version_is_lower

	_version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
	_version_not_supported = True

if _version_not_supported:
	raise RuntimeError(
		f"The grpc package installed is at version {GRPC_VERSION},"
		+ " but the generated code in tests/protos/mls_pb2_grpc.py depends on"
		+ f" grpcio>={GRPC_GENERATED_VERSION}."
		+ f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
		+ f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
	)


class MLSSwarmStub(object):
	"""Missing associated documentation comment in .proto file."""

	def __init__(self, channel):
		"""Constructor.

		Args:
		    channel: A grpc.Channel.
		"""
		self.JoinSwarm = channel.unary_unary(
			"/puremls.MLSSwarm/JoinSwarm",
			request_serializer=tests_dot_protos_dot_mls__pb2.JoinRequest.SerializeToString,
			response_deserializer=tests_dot_protos_dot_mls__pb2.JoinResponse.FromString,
			_registered_method=True,
		)
		self.DeliverWelcome = channel.unary_unary(
			"/puremls.MLSSwarm/DeliverWelcome",
			request_serializer=tests_dot_protos_dot_mls__pb2.WelcomeMessage.SerializeToString,
			response_deserializer=tests_dot_protos_dot_mls__pb2.Ack.FromString,
			_registered_method=True,
		)
		self.ListenWelcomes = channel.unary_stream(
			"/puremls.MLSSwarm/ListenWelcomes",
			request_serializer=tests_dot_protos_dot_mls__pb2.ListenRequest.SerializeToString,
			response_deserializer=tests_dot_protos_dot_mls__pb2.WelcomeMessage.FromString,
			_registered_method=True,
		)


class MLSSwarmServicer(object):
	"""Missing associated documentation comment in .proto file."""

	def JoinSwarm(self, request, context):
		"""Bob publishes his KeyPackage to the Directory"""
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details("Method not implemented!")
		raise NotImplementedError("Method not implemented!")

	def DeliverWelcome(self, request, context):
		"""Alice sends a Sealed Welcome to Bob"""
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details("Method not implemented!")
		raise NotImplementedError("Method not implemented!")

	def ListenWelcomes(self, request, context):
		"""Bob checks his inbox for Welcomes"""
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details("Method not implemented!")
		raise NotImplementedError("Method not implemented!")


def add_MLSSwarmServicer_to_server(servicer, server):
	rpc_method_handlers = {
		"JoinSwarm": grpc.unary_unary_rpc_method_handler(
			servicer.JoinSwarm,
			request_deserializer=tests_dot_protos_dot_mls__pb2.JoinRequest.FromString,
			response_serializer=tests_dot_protos_dot_mls__pb2.JoinResponse.SerializeToString,
		),
		"DeliverWelcome": grpc.unary_unary_rpc_method_handler(
			servicer.DeliverWelcome,
			request_deserializer=tests_dot_protos_dot_mls__pb2.WelcomeMessage.FromString,
			response_serializer=tests_dot_protos_dot_mls__pb2.Ack.SerializeToString,
		),
		"ListenWelcomes": grpc.unary_stream_rpc_method_handler(
			servicer.ListenWelcomes,
			request_deserializer=tests_dot_protos_dot_mls__pb2.ListenRequest.FromString,
			response_serializer=tests_dot_protos_dot_mls__pb2.WelcomeMessage.SerializeToString,
		),
	}
	generic_handler = grpc.method_handlers_generic_handler("puremls.MLSSwarm", rpc_method_handlers)
	server.add_generic_rpc_handlers((generic_handler,))
	server.add_registered_method_handlers("puremls.MLSSwarm", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MLSSwarm(object):
	"""Missing associated documentation comment in .proto file."""

	@staticmethod
	def JoinSwarm(
		request,
		target,
		options=(),
		channel_credentials=None,
		call_credentials=None,
		insecure=False,
		compression=None,
		wait_for_ready=None,
		timeout=None,
		metadata=None,
	):
		return grpc.experimental.unary_unary(
			request,
			target,
			"/puremls.MLSSwarm/JoinSwarm",
			tests_dot_protos_dot_mls__pb2.JoinRequest.SerializeToString,
			tests_dot_protos_dot_mls__pb2.JoinResponse.FromString,
			options,
			channel_credentials,
			insecure,
			call_credentials,
			compression,
			wait_for_ready,
			timeout,
			metadata,
			_registered_method=True,
		)

	@staticmethod
	def DeliverWelcome(
		request,
		target,
		options=(),
		channel_credentials=None,
		call_credentials=None,
		insecure=False,
		compression=None,
		wait_for_ready=None,
		timeout=None,
		metadata=None,
	):
		return grpc.experimental.unary_unary(
			request,
			target,
			"/puremls.MLSSwarm/DeliverWelcome",
			tests_dot_protos_dot_mls__pb2.WelcomeMessage.SerializeToString,
			tests_dot_protos_dot_mls__pb2.Ack.FromString,
			options,
			channel_credentials,
			insecure,
			call_credentials,
			compression,
			wait_for_ready,
			timeout,
			metadata,
			_registered_method=True,
		)

	@staticmethod
	def ListenWelcomes(
		request,
		target,
		options=(),
		channel_credentials=None,
		call_credentials=None,
		insecure=False,
		compression=None,
		wait_for_ready=None,
		timeout=None,
		metadata=None,
	):
		return grpc.experimental.unary_stream(
			request,
			target,
			"/puremls.MLSSwarm/ListenWelcomes",
			tests_dot_protos_dot_mls__pb2.ListenRequest.SerializeToString,
			tests_dot_protos_dot_mls__pb2.WelcomeMessage.FromString,
			options,
			channel_credentials,
			insecure,
			call_credentials,
			compression,
			wait_for_ready,
			timeout,
			metadata,
			_registered_method=True,
		)
